quarkus.application.name=game

quarkus.datasource.db-kind=mariadb
quarkus.flyway.migrate-at-start=true

quarkus.otel.enabled=true
quarkus.otel.service.name=game
quarkus.otel.exporter.otlp.protocol=grpc

%local.quarkus.datasource.jdbc.url=${DB_URL:jdbc:mariadb://localhost:3306/game}
%local.quarkus.datasource.username=${DB_USERNAME:chessland}
%local.quarkus.datasource.password=${DB_PASSWORD:chessland-local}
%local.quarkus.otel.exporter.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}

%dev.quarkus.datasource.jdbc.url=${DB_URL}
%dev.quarkus.datasource.username=${DB_USERNAME}
%dev.quarkus.datasource.password=${DB_PASSWORD}
%dev.quarkus.otel.exporter.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}

%prod.quarkus.datasource.jdbc.url=${DB_URL}
%prod.quarkus.datasource.username=${DB_USERNAME}
%prod.quarkus.datasource.password=${DB_PASSWORD}
%prod.quarkus.otel.exporter.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}