name: Deploy Dev

on:
  workflow_run:
    workflows:
      - Build Images
    types:
      - completed
    branches:
      - develop

concurrency:
  group: chessland-dev
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    environment:
      name: development

    steps:
      - name: Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          COMPOSE_DIR: ${{ secrets.COMPOSE_DIR }}
          GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: |
          mkdir -p ~/.ssh

          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts

          printf '%s' "$GHCR_TOKEN" | \
            ssh "$SSH_USER@$SSH_HOST" \
            "docker login ghcr.io -u '$GHCR_USERNAME' --password-stdin"

          ssh "$SSH_USER@$SSH_HOST" "
            cd '$COMPOSE_DIR' &&
            docker compose --env-file .env -f docker-compose.dev.yml pull &&
            docker compose --env-file .env -f docker-compose.dev.yml up -d --remove-orphans
          "